version: "3.9"

services:
  app:
    build: .
    command: "-S 0.0.0.0:8080"
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - db
    working_dir: /app
    tty: true
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
      - "33060:33060"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: app
